%{?!ros_distro:%global ros_distro lyrical}
%global pkg_name rqt_gauges
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-lyrical-rqt-gauges
Version:        0.0.3
Release:        3%{?dist}
Summary:        ROS %{pkg_name} package

License:        BSD Clause 3
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

BuildRequires:  bloom-rpm-macros
BuildRequires:  python%{python3_pkgversion}-devel

%{?bloom_package}

%description
Visualization plugin for several sensors.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Requires:       %{name}-runtime = %{version}-%{release}

%description devel
Visualization plugin for several sensors.


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
Visualization plugin for several sensors.


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%py3_build


%install
%py3_install -- --prefix "%{bloom_prefix}"


%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "^\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%license LICENSE
%{bloom_prefix}


%changelog
* Wed Apr 29 2026 Eloy Bricneo <eloy.briceno@ekumenlabs.com> - 0.0.3-3
- Autogenerated by Bloom

* Tue Apr 28 2026 Eloy Bricneo <eloy.briceno@ekumenlabs.com> - 0.0.3-2
- Autogenerated by Bloom

* Tue Apr 21 2026 Eloy Bricneo <eloy.briceno@ekumenlabs.com> - 0.0.3-1
- Autogenerated by Bloom
