%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

Name:           ros-kilted-rqt-gauges
Version:        0.0.3
Release:        2%{?dist}%{?release_suffix}
Summary:        ROS rqt_gauges package

License:        BSD Clause 3
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-kilted-ament-index-python
Requires:       ros-kilted-qt-gui
Requires:       ros-kilted-qt-gui-py-common
Requires:       ros-kilted-rclpy
Requires:       ros-kilted-rqt-gui
Requires:       ros-kilted-rqt-gui-py
Requires:       ros-kilted-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-kilted-ament-flake8
BuildRequires:  ros-kilted-ament-xmllint
%endif

%description
Visualization plugin for several sensors.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/kilted"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
%license LICENSE
/opt/ros/kilted

%changelog
* Wed Apr 23 2025 Eloy Bricneo <eloy.briceno@ekumenlabs.com> - 0.0.3-2
- Autogenerated by Bloom

* Thu Mar 14 2024 Eloy Bricneo <eloy.briceno@ekumenlabs.com> - 0.0.3-1
- Autogenerated by Bloom

* Wed Mar 06 2024 Eloy Bricneo <eloy.briceno@ekumenlabs.com> - 0.0.2-2
- Autogenerated by Bloom

